# Generated by Django 3.2 on 2021-04-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categoria_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
