# Generated by Django 3.2 on 2021-04-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0002_auto_20210424_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servixio', 'verbose_name_plural': 'servixios'},
        ),
    ]
