# Generated by Django 3.2 on 2021-04-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0003_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
